REM SIMPLE DODGE GAME
dim SPRX, SPRY, SPRACT, SPRXADD, SPRWHIT, SPRHITS
dim FRCOUNT, CURRENT
dim PY
dim STICK

U235MOD(0)
SPRX=8: SPRY=12: SPRACT=4: SPRXADD=16: SPRWHIT=112: SPRHITS=132
FRCOUNT=0: CURRENT=0
PY=100

REM MAIN LOOP
do
	FRCOUNT=FRCOUNT+1
	IF FRCOUNT=10 THEN 
		call newenemy 'REM ADD NEW ENEMY
	ENDIF
	STICK=U235PAD(1)
	IF (STICK=1 AND PY>20) THEN
		PY=PY-2
	ENDIF
	IF (STICK=2 AND PY<200) THEN
		PY=PY+2
	endif
	RSETOBJ(1,SPRY,PY<<16)
	IF RHIT(1,1,2,22)<>-1 THEN
		U235SND(0,4)
	endif
	RUPDALL(0)
loop

REM NEW ENEMY
sub newenemy
	RSETOBJ(2+CURRENT,SPRX,352<<16)
	RSETOBJ(2+CURRENT,SPRY,INT((integer)(RND*200)<<16))
	RSETOBJ(2+CURRENT,SPRWHIT,-1)
	RSETOBJ(2+CURRENT,SPRHITS,1)
	RSETOBJ(2+CURRENT,SPRXADD,-2<<16)
	RSETOBJ(2+CURRENT,SPRACT,1)
	CURRENT=CURRENT+1
	IF CURRENT=20 THEN
		CURRENT=0
	ENDIF
	FRCOUNT=0
end sub

